EXTENSION_KEY = "jwt-login"


CONFIG_DEFAULTS = {
    'JWT_ALGORITHM': 'HS256',
    'JWT_LEEWAY': 10,
    'JWT_AUTH_HEADER_PREFIX': 'JWT',
    'JWT_ACCESS_TOKEN_LIFETIME': 5 * 60,
    'JWT_REFRESH_TOKEN_LIFETIME': 60 * 60 * 24 * 7,
    'JWT_NOT_BEFORE_DELTA': 0,
}
