"""empty message

Revision ID: ac36d0f7684d
Revises: 
Create Date: 2022-03-07 23:31:12.775824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac36d0f7684d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('salt', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=1024), nullable=False),
    sa.Column('country_code', sa.String(length=8), nullable=True),
    sa.Column('phone_number', sa.String(length=16), nullable=True),
    sa.Column('last_login_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_email'), 'account', ['email'], unique=False)
    op.create_index(op.f('ix_account_phone_number'), 'account', ['phone_number'], unique=False)
    op.create_index(op.f('ix_account_uuid'), 'account', ['uuid'], unique=True)
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_account_id'), 'profile', ['account_id'], unique=False)
    op.create_index(op.f('ix_profile_username'), 'profile', ['username'], unique=False)
    op.create_index(op.f('ix_profile_uuid'), 'profile', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_uuid'), table_name='profile')
    op.drop_index(op.f('ix_profile_username'), table_name='profile')
    op.drop_index(op.f('ix_profile_account_id'), table_name='profile')
    op.drop_table('profile')
    op.drop_index(op.f('ix_account_uuid'), table_name='account')
    op.drop_index(op.f('ix_account_phone_number'), table_name='account')
    op.drop_index(op.f('ix_account_email'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
